version: '1.0'
name: pipeline-20220715
displayName: typescript编译测试
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
stages:
  - name: stage-43081a46
    displayName: 编译
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - npm install && rm -rf ./dist && npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
permissions:
  - role: admin
    members: []
