name: Build and deploy main

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and deploy main
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - uses: pnpm/action-setup@v2.2.3
        with:
          version: latest

      # pass --base for application to work under GitHub pages
      - name: Install
        run: pnpm install
      
      - name: Build
        run: pnpm run build -- --base=/${{ github.event.repository.name }}/
          
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist

      - name: Publish deployed code 
        uses: actions/upload-artifact@v2
        with:
          name: published
          path: dist
